resource "local_sensitive_file" "env_terraform_file" {
  filename = "${path.module}/../.env.terraform"
  content  = <<-EOT
    # ==========================================
    # AUTO-GENERATED BY TERRAFORM
    # DO NOT CHANGE IT MANUALLY
    # ==========================================

    TOMORROW_API_KEY=${var.tomorrow_api_key}
    
    BRONZE_BUCKET_NAME=${local.bronze_bucket.name}
    SILVER_BUCKET_NAME=${local.silver_bucket.name}
    BIGQUERY_DATASET=${local.bigquery_dataset.dataset_id}
    BIGQUERY_TABLE=${local.bigquery_table.table_id}

  EOT
}

resource "local_sensitive_file" "env_file" {
  filename = "${path.module}/../.env"
  content  = <<-EOT
    # ==========================================
    # AUTO-GENERATED BY TERRAFORM
    # DO NOT CHANGE IT MANUALLY
    # ==========================================

    AIRFLOW_UID=${local.airflow_uid}

    FERNET_KEY=${random_id.airflow_fernet_key.b64_url}
    _PIP_ADDITIONAL_REQUIREMENTS=${var.pip_additional_requirements}
    AIRFLOW_PROJ_DIR=./airflow  
    
    PROJECT_ID="cloud-task-weather"
  EOT
}

resource "random_id" "airflow_fernet_key" {
  byte_length = 32
}
