resource "local_sensitive_file" "env_file" {
  filename = "${path.module}/../.env.terraform"
  content  = <<-EOT
    # ==========================================
    # AUTO-GENERATED BY TERRAFORM
    # DO NOT CHANGE IT MANUALLY
    # ==========================================

    TOMORROW_API_KEY=${var.tomorrow_api_key}
    BRONZE_BUCKET_NAME=${google_storage_bucket.created_buckets["bronze"].name}

    _PIP_ADDITIONAL_REQUIREMENTS=${var.pip_additional_requirements}
    FERNET_KEY=${random_id.airflow_fernet_key.b64_url}
  EOT
}

resource "random_id" "airflow_fernet_key" {
  byte_length = 32
}
