resource "local_sensitive_file" "env_terraform_file" {
  filename = "${path.module}/../.env.terraform"
  content  = <<-EOT
    # ==========================================
    # AUTO-GENERATED BY TERRAFORM
    # DO NOT CHANGE IT MANUALLY
    # ==========================================

    TOMORROW_API_KEY=${var.tomorrow_api_key}
    
    BRONZE_BUCKET_NAME=${google_storage_bucket.created_buckets["bronze"].name}
    SILVER_BUCKET_NAME=${google_storage_bucket.created_buckets["silver"].name}
    BIGQUERY_DATASET=${google_bigquery_dataset.weather_gold_dataset.dataset_id}
    BIGQUERY_TABLE=${google_bigquery_table.weather_gold_table.table_id}

  EOT
}

resource "local_sensitive_file" "env_file" {
  filename = "${path.module}/../.env"
  content  = <<-EOT
    # ==========================================
    # AUTO-GENERATED BY TERRAFORM
    # CHANGE ONLY "AIRFLOW_UID" IF NECESSARY
    # ==========================================

    # Требуется 1 раз указать ID пользователя Aiflow
    # На Windows стоит по умолчанию 50000
    # На Lunix, чтобы узнать ID пользователя, надо прописать команду "id -u"
    AIRFLOW_UID=50000

    FERNET_KEY=${random_id.airflow_fernet_key.b64_url}
    _PIP_ADDITIONAL_REQUIREMENTS=${var.pip_additional_requirements}
    AIRFLOW_PROJ_DIR=./airflow  
    
    PROJECT_ID="cloud-task-weather"
  EOT
}

resource "random_id" "airflow_fernet_key" {
  byte_length = 32
}
